<h1>NUMPY</h1>

In [2]:
import numpy as np

In [4]:
mat1D = np.array([1,2,3,4,5,6,7,8,9])
mat2D = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])

In [16]:
print(f"nilai Matriks 1D:\n{mat1D}")
print(f"nilai Matriks 2D:\n{mat2D}")

nilai Matriks 1D:
[1 2 3 4 5 6 7 8 9]
nilai Matriks 2D:
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [30]:
print(mat1D[1]) #2
print(mat2D[1]) #[50,60,80,80]
print(mat2D[1][2]) #70
print(f"mat1D ditambah dengan 10:\n{mat1D + 10}")
print(f"mat2D ditambah dengan 2:\n{mat2D + 2}")

2
[50 60 70 80]
70
mat1D ditambah dengan 10:
[11 12 13 14 15 16 17 18 19]
mat2D ditambah dengan 2:
[[ 12  22  32  42]
 [ 52  62  72  82]
 [ 92 102 112 122]]


In [34]:
print(mat1D.shape)
print(mat1D.size)
print(f"Bentuk dari mat2D: {mat2D.shape}")
print(f"Ukuran dari mat2D: {mat2D.size}")

(9,)
9
Bentuk dari mat2D: (3, 4)
Ukuran dari mat2D: 12


In [89]:
#Matriks Spesial
mZero = np.zeros([4,4])
mOne = np.ones([4,4])
mIdentity = np.eye(4)
mFull = np.full((4,4),7)
mRandom1D = np.random.rand(5)
mRandom2D = np.random.rand(3,4)
mRandom1DInt = np.random.randint(1,10,size=8)
mRandom2DInt = np.random.randint(1,10,size=(3,4))

In [91]:
print(f"Matrix Zero:\n{mZero}")
print(f"Matrix One:\n{mOne}")
print(f"Matrix Identity:\n{mIdentity}")
print(f"Matrix Full:\n{mFull}")
print(f"Matrix Random 1D:\n{mRandom1D}")
print(f"Matrix Random 2D:\n{mRandom2D}")
print(f"Matrix Integer 1D:\n{mRandom1DInt}")
print(f"Matrix Integer 2D:\n{mRandom2DInt}")

Matrix Zero:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Matrix One:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matrix Identity:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Matrix Full:
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
Matrix Random 1D:
[0.0114261  0.86889868 0.35930037 0.01856445 0.62870753]
Matrix Random 2D:
[[0.33817301 0.05915884 0.21617227 0.5945244 ]
 [0.37292988 0.37824661 0.18992116 0.80697662]
 [0.76330791 0.36233025 0.84059376 0.73057818]]
Matrix Integer 1D:
[4 3 3 3 5 6 4 8]
Matrix Integer 2D:
[[7 8 9 1]
 [1 7 9 2]
 [7 1 6 6]]


In [105]:
#Operasi Aritmatika
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])

r1 = np.add(x,y) #add ditambah
r2 = np.dot(x,y) #dot dikali dengan cara dot product

print(f"Hasil penjumlahan x dan y: {r1}")
print(f"Hasil perkalian dot product: {r2}")

Hasil penjumlahan x dan y: [ 7  9 11 13 15]
Hasil perkalian dot product: 130


In [119]:
#Fungsi dasar statistik
nilaiProgramming = np.array([100,90,90,50,80,60,50,85])
print(f"Nilai programming: {nilaiProgramming}")
print(f"Nilai terkecil: {np.min(nilaiProgramming)}")
print(f"Nilai terbesar: {np.max(nilaiProgramming)}")
print(f"Nilai rata-rata: {np.mean(nilaiProgramming)}")
print(f"Nilai total: {np.sum(nilaiProgramming)}")
print(f"Nilai Standar Deviasi: {np.std(nilaiProgramming)}")
print(f"Nilai Tengah: {np.median(nilaiProgramming)}")

Nilai programming: [100  90  90  50  80  60  50  85]
Nilai terkecil: 50
Nilai terbesar: 100
Nilai rata-rata: 75.625
Nilai total: 605
Nilai Standar Deviasi: 18.275239396516806
Nilai Tengah: 82.5


In [131]:
#Operasi Bentuk
matX = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(f"Matriks X:\n{matX}")
print(f"Matriks X diubah bentuknya menjadi:\n{matX.reshape(10,1)}") #yang kiri (10) kebawah, yang kanan (1) kekanan
print(f"Matriks X diubah menjadi benruk flat:\n{matX.flatten()}")

Matriks X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Matriks X diubah bentuknya menjadi:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
Matriks X diubah menjadi benruk flat:
[ 1  2  3  4  5  6  7  8  9 10]


In [141]:
#Filtering
lulus = nilaiProgramming[nilaiProgramming > 50]

print(f"Daftar nilai yang lulus:{lulus}")
print(f"Jumlah yang lulus:{lulus.size}")

Daftar nilai yang lulus:[100  90  90  80  60  85]
Jumlah yang lulus:6


<b1>Contoh Kasus</b1>
bualah contoh dataset sebanyak 10.000 untuk proses klasifikasi nasabah kartu kredit
<ol>
    <li>Usia: 17 - 60</li>
    <li>Gender: L/P</li>
    <li>Gaji: 1jt - 3jt, 3jt - 5jt, 5jt - 10jt</li>
    <li>Jumlah anak: 0 - 6</li>
</ol>

In [196]:
import numpy as np
import pandas as pd

n_data = 10000
usia = np.random.randint(17,61,size=n_data)
gender = np.random.choice(['L','P'],size=n_data)
gaji = np.random.choice(['1-3jt','3-5jt','5-10jt'],size=n_data)
anak = np.random.randint(0,7,size=n_data)

df = pd.DataFrame({
    'Usia' : usia,
    'Gender' : gender,
    'Gaji' : gaji,
    'Jumlah-Anak' : anak
})

df.to_csv('data_calon_nasabah.csv')

print(df.info())
print(df.head())
print(df.shape)
print(df.size)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Usia         10000 non-null  int32 
 1   Gender       10000 non-null  object
 2   Gaji         10000 non-null  object
 3   Jumlah-Anak  10000 non-null  int32 
dtypes: int32(2), object(2)
memory usage: 234.5+ KB
None
   Usia Gender    Gaji  Jumlah-Anak
0    45      L  5-10jt            3
1    51      L   3-5jt            3
2    23      L   1-3jt            4
3    37      L   1-3jt            2
4    56      L   3-5jt            3
(10000, 4)
40000


In [204]:
#1. Tampilkan usia calon nasabah yang paling muda
#2. Tampilkan usia calon nasbaha yang paling tua
#3. Tampilkan gaji rata-rata
#4. Tampilkan berapa jumlah laki-laki
#5. Tampilkan berapa jumlah perempuan

print(f"Usia calon nasabah yang paling muda adalah:{df['Usia'].min()}") #Nomor 1

print(f"Usia calon nasabah yang paling muda adalah:{df['Usia'].max()}") #Nomor 2

#rata-rata tidak bisa karena tipe gaji adalah "KATEGORI" Nomor 3

laki = df[df['Gender'] == 'L']
print(f"Jumlah laki-lakinya adalah: {laki.size/4}")
print(f"Jumlah laki-lakinya adalah: {laki['Gender'].size}") #Nomor 4

cewe = df[df['Gender'] == 'P']
print(f"Jumlah perempuannya adalah: {cewe.size/4}")
print(f"Jumlah perempuannya adalah: {cewe['Gender'].size}") #Nomor 5

Usia calon nasabah yang paling muda adalah:17
Usia calon nasabah yang paling muda adalah:60
Jumlah laki-lakinya adalah: 4965.0
Jumlah laki-lakinya adalah: 4965
Jumlah perempuannya adalah: 5035.0
Jumlah perempuannya adalah: 5035
